minimumReleaseAgeExclude: [ '@typescript-eslint/eslint-plugin@8.69.0 || 8.70.1', '@typescript-eslint/parser@8.69.0 || 8.70.1', '@typescript-eslint/project-service@8.69.0 || 8.70.1', '@typescript-eslint/scope-manager@8.69.0 || 8.70.1', '@typescript-eslint/tsconfig-utils@8.69.0 || 8.70.1', '@typescript-eslint/type-utils@8.69.0 || 8.70.1', '@typescript-eslint/types@8.69.0 || 8.70.1', '@typescript-eslint/typescript-estree@8.69.0 || 8.70.1', '@typescript-eslint/utils@8.69.0 || 8.70.1', '@typescript-eslint/visitor-keys@8.69.0 || 8.70.1', typescript-eslint@8.69.0 || 8.70.1, undici@8.10.1 ]

minimumReleaseAge: 4320
ignoredBuiltDependencies: []
strictDepBuilds: true

allowBuilds:
  core-js: true
  lmdb: true
  msgpackr-extract: true
  '@parcel/watcher': true
  esbuild: true

overrides:
  undici: 8.10.1
  picomatch: '>=4.0.4'
  piscina: '>=5.1.5'
  esbuild: '>=0.28.1'
  '@babel/core': '>=7.29.1'
